// Returns string arrays associated with the application's preset categories; each category includes an icon
// and a title/label. Each icon is associated with several keywords.

// A set of preset categories and their titles/labels.
const getPresetCategories = () => [
  { title: "Bear Aware", icon: "bear" },
  { title: "Books & Guides", icon: "book" },
  { title: "Bug Protection", icon: "bug" },
  { title: "Clothing", icon: "clothing" },
  { title: "Dental", icon: "dental" },
  { title: "Electronics", icon: "electronics" },
  { title: "Fire Starting", icon: "fire" },
  { title: "Food", icon: "food" },
  { title: "Hydration", icon: "water" },
  { title: "Hygiene", icon: "toiletpaper" },
  { title: "Light", icon: "light" },
  { title: "Medical", icon: "medical" },
  { title: "Mountaineering", icon: "mountain" },
  { title: "Navigation", icon: "compass" },
  { title: "Storage", icon: "storage" },
  { title: "Photography", icon: "camera" },
  { title: "Documents & ID", icon: "wallet" },
  { title: "Shelter", icon: "tent" },
  { title: "Sleeping", icon: "sleep" },
  { title: "Snow Gear", icon: "snow" },
  { title: "Sun Safety", icon: "sun" },
  { title: "Tools", icon: "tools" },
  { title: "Other", icon: "folder" },
];

// Keywords assigned to each category icon.
const getPresetCategoryKeywords = () => {
  return {
    tent: ["shelter", "tent", "hammock"],
    sleep: ["sleeping", "mattress", "sleeping pad", "foam"],
    bear: ["bear"],
    storage: ["pack", "bag", "sack"],
    clothing: ["clothing", "gloves", "socks", "boots", "bandanna", "gaiters"],
    compass: [
      "navigation",
      "gps",
      "map",
      "guide",
      "compass",
      "tide chart",
      "star chart",
    ],
    water: [
      "water",
      "hydration",
      "drinking",
      "purification",
      "purifier",
      "filter",
      "filtration",
    ],
    folder: ["default"],
    food: [
      "food",
      "dehydrated",
      "meal",
      "snack",
      "breakfast",
      "lunch",
      "dinner",
      "eating",
      "calories",
      "kitchen",
      "utensils",
      "fuel",
      "stove",
      "jetboil",
      "silverware",
    ],
    medical: ["medical", "first-aid", "first aid"],
    camera: ["photography", "camera"],
    tools: [
      "tool",
      "poles",
      "knife",
      "axe",
      "multi-tool",
      "multitool",
      "paddle",
      "boat",
      "binoculars",
      "kayak",
    ],
    light: ["light", "lamp", "headlamp", "flashlight", "lantern"],
    fire: ["fire", "matches", "flint", "tinder"],
    dental: ["dental", "floss", "retainer", "tooth", "mouthwash", "toothbrush"],
    toiletpaper: ["hygiene", "bathroom", "pee", "poop", "wag bag", "toilet"],
    book: ["book", "kindle"],
    bug: [
      "bug",
      "insect",
      "mosquito",
      "deet",
      "insect repellent",
      "citronella",
      "flies",
    ],
    electronics: [
      "electronics",
      "phone",
      "batteries",
      "charger",
      "iphone",
      "watch",
      "monitor",
      "speakers",
      "headphones",
      "airpods",
      "computer",
      "tablet",
      "power",
      "radio",
    ],
    sun: ["sunscreen", "upf", "spf"],
    snow: [
      "crampons",
      "traction",
      "microspikes",
      "snow",
      "ski",
      "splitboard",
      "avalanche",
    ],
    wallet: [
      "identification",
      "wallet",
      "money",
      "permit",
      "receipt",
      "reservation",
    ],
    helmet: [
      "climbing",
      "helmet",
      "carabiners",
      "ice pick",
      "ascend",
      "descend",
      "ropes",
      "belay",
      "rappel",
      "webbing",
      "bouldering",
      "slacklines",
      "chalk",
    ],
  };
};

export { getPresetCategories, getPresetCategoryKeywords };
